server.port=${SPRING_PORT}

spring.datasource.url=${SPRING_DB_URL}
spring.datasource.username=${SPRING_DB_USERNAME:postgres}
spring.datasource.password=${SPRING_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

logging.level.org.springframework.jdbc=DEBUG
logging.level.org.flywaydb=DEBUG

spring.datasource.hikari.connection-timeout=${SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT}

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.template.default-topic=${SPRING_KAFKA_DEFAULT_TOPIC}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

logging.level.org.springframework.kafka=DEBUG
logging.level.org.apache.kafka=INFO